[build]
  publish = "dist"
  command = "pnpm install && pnpm build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/data/views.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[context.production.environment]
NETLIFY_OTEL_PLUGIN_DISABLED = "true"

[context.deploy-preview.environment]
  NETLIFY_BLOBS_CONTEXT = "deploy-preview"

[context.branch-deploy.environment]
  NETLIFY_BLOBS_CONTEXT = "branch-deploy"